283,100
284,"Capital List"
11,20151013011451
274,
18,0
275,358
{[CapitalList].[CapitalList].[Total],[CapitalList].[CapitalList].[1],[CapitalList].[CapitalList].[2],[CapitalList].[CapitalList].[3],[CapitalList].[CapitalList].[4],[CapitalList].[CapitalList].[5],[CapitalList].[CapitalList].[6],[CapitalList].[CapitalList].[7],[CapitalList].[CapitalList].[8],[CapitalList].[CapitalList].[9],[CapitalList].[CapitalList].[10]}
278,0
281,0
270,0
